export const rows = [
  {
    id: 1,
    avatar: '',
    full_name: 'Cuaderno Standford',
    post: 'Technical Writer',
    email: 'pbice14@ameblo.jp',
    city: 'Shanlian',
    start_date: '03/02/2016',
    price: 3.2,
    stock: '65',
    experience: '5 Years',
    status: 2
  },
  {
    id: 2,
    avatar: '',
    full_name: 'Lapicero Faber Castell',
    post: 'Biostatistician',
    email: 'lorsi15@wp.com',
    city: 'Dengteke',
    start_date: '12/10/2018',
    price: 1,
    stock: '64',
    experience: '4 Years',
    status: 2
  },
  {
    id: 3,
    avatar: '8.png',
    full_name: 'Cuaderno Loro',
    post: 'Environmental Tech',
    email: 'dchaplyn16@nymag.com',
    city: 'Lattes',
    start_date: '01/23/2019',
    price: 2,
    stock: '38',
    experience: '8 Years',
    status: 2
  },
  {
    id: 4,
    avatar: '',
    full_name: 'Juguete interactivo',
    post: 'Human Resources Manager',
    email: 'wbygraves17@howstuffworks.com',
    city: 'Zlaté Hory',
    start_date: '09/07/2016',
    price: 25.5,
    stock: '37',
    experience: '7 Years',
    status: 3
  },
  {
    id: 5,
    avatar: '7.png',
    full_name: 'Papel foto',
    post: 'Operator',
    email: 'mbodechon18@1und1.de',
    city: 'Itō',
    start_date: '07/23/2018',
    price: 2,
    stock: '61',
    experience: '1 Year',
    status: 3
  },
  {
    id: 6,
    avatar: '1.png',
    full_name: 'Papel crepe',
    post: 'Recruiting Manager',
    email: 'mde19@purevolume.com',
    city: 'San Diego',
    start_date: '02/10/2018',
    price: 1.5,
    stock: '47',
    experience: '7 Years',
    status: 3
  },
  {
    id: 7,
    avatar: '4.png',
    full_name: 'Block iris',
    post: 'Cost Accountant',
    email: 'hchatelot1a@usatoday.com',
    city: 'Mercedes',
    start_date: '11/23/2016',
    price: 2.5,
    stock: '64',
    experience: '4 Years',
    status: 2
  },
  {
    id: 8,
    avatar: '',
    full_name: 'Folder tamaño carta',
    post: 'Registered Nurse',
    email: 'gmccrum1b@icio.us',
    city: 'Nggalak',
    start_date: '04/19/2018',
    price: 3,
    stock: '63',
    experience: '3 Years',
    status: 2
  },
  {
    id: 9,
    avatar: '5.png',
    full_name: 'Caja de colores',
    post: 'VP Accounting',
    email: 'kstilldale1c@chronoengine.com',
    city: 'Slavs’ke',
    start_date: '03/18/2017',
    price:4,
    stock: '56',
    experience: '6 Years',
    status: 3
  },
  {
    id: 10,
    avatar: '4.png',
    full_name: 'Cuadernos argollados',
    post: 'Research Assistant',
    email: 'mumbert1d@digg.com',
    city: 'Chorotis',
    start_date: '05/13/2019',
    price: 6.5,
    stock: '43',
    experience: '3 Years',
    status: 2
  },
  {
    id: 11,
    avatar: '2.png',
    full_name: 'Tizas',
    post: 'Human Resources Assistant',
    email: 'eebsworth2m@sbwire.com',
    city: 'Puzi',
    start_date: '09/27/2018',
    price: 1,
    stock: '27',
    experience: '2 Years',
    status: 2
  }
]
